language: java
addons:
  sonarcloud:
    organization: "kyriosdata-github"
    token:
      secure: "qwcil4H2BMkDh4FAJPVOdIBa5li4GkeXPgZ1MNa0EshUcZ0tBCaq1RH/HvAI/hFY9P6zzN5lnHwWk7SvXGxYgUrJviQ48Vrlnx2iDS7ubUgtxm0z64GOn3KT5keQ+vnJgUz4urPlYB4rRn5fzs4Vi5GdJA8xjcsdX2CBiWbbwgEsJw/lDQh7YgvpL6QSGbZKa45z69FXuF+650OBBC8PfoOoxP7olEWtfBqMCzKJn6vHYYI4XGwNuRbN1v4slV6LqiOD3+ziv5q7IpPnjihGpMJBG4Ca2RSjTQMFEBBGZpzPkX3H8giGCqpLmgaPwTq5+6U9npYsk6gGCqDPRbHhgcweJXLwONKWQbYhvpgNyShPElxG38pyiKIHAfdvbsRJvusPWn60lvnv/R3ub/Qy2KGS6MxF6PRMrmtkOr6i1A4Gm4NYK548JX1sOfMliVEt/rUud+tz4K5tdIfXemvXz/ito1AxAqYU5ZYKJvT01d7LMzZNynnbi8f9M3Y+r1AQsDGzw+svTf66CbfO+fLpujDzejwyhRdUl90NpctvQPGpjRvTsUAOTY8fR9mB7/whaHqC8MMjyEHKXCJMCCfE3BRy2M8vjPuUSXRM1wTunUr4MrO3QsBaZrdu0aK7/SrxM3yap38XVqVHpHCgyP5ODQxU0F2nZb0kZ5+ozQh+M8c="

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"

env:
  global:
    secure: qwcil4H2BMkDh4FAJPVOdIBa5li4GkeXPgZ1MNa0EshUcZ0tBCaq1RH/HvAI/hFY9P6zzN5lnHwWk7SvXGxYgUrJviQ48Vrlnx2iDS7ubUgtxm0z64GOn3KT5keQ+vnJgUz4urPlYB4rRn5fzs4Vi5GdJA8xjcsdX2CBiWbbwgEsJw/lDQh7YgvpL6QSGbZKa45z69FXuF+650OBBC8PfoOoxP7olEWtfBqMCzKJn6vHYYI4XGwNuRbN1v4slV6LqiOD3+ziv5q7IpPnjihGpMJBG4Ca2RSjTQMFEBBGZpzPkX3H8giGCqpLmgaPwTq5+6U9npYsk6gGCqDPRbHhgcweJXLwONKWQbYhvpgNyShPElxG38pyiKIHAfdvbsRJvusPWn60lvnv/R3ub/Qy2KGS6MxF6PRMrmtkOr6i1A4Gm4NYK548JX1sOfMliVEt/rUud+tz4K5tdIfXemvXz/ito1AxAqYU5ZYKJvT01d7LMzZNynnbi8f9M3Y+r1AQsDGzw+svTf66CbfO+fLpujDzejwyhRdUl90NpctvQPGpjRvTsUAOTY8fR9mB7/whaHqC8MMjyEHKXCJMCCfE3BRy2M8vjPuUSXRM1wTunUr4MrO3QsBaZrdu0aK7/SrxM3yap38XVqVHpHCgyP5ODQxU0F2nZb0kZ5+ozQh+M8c=

jdk:
  - oraclejdk8
