language: java

addons:
  sonarcloud:
    organization: "kyriosdata-github"
    token:
      ssecure: "YjwGQjffXcLj1dLsAEOkd25VKFgeI+iahOtq7dJ+9CY0M1PB/kHzFaqkPwBWLEhHV0Uqv6jNKwoHvtMAnHxoC3DKFxsMNQ/Kwy5weWBxGE0TGLeVaTBU+qn4/uu+p+TzkanrXPSifhLIfJEub9UQ3NgRS/N0glpSCUWTaDZ/aw3E0uOlQQAhIaLvvuCevIygPvhbTCU4p4qgZM0vKwDKRr95uu3GYlKX3IsaiXNijBro0Tjxk66xodj75EYw2F0cCNSIp9bvKvOA+csTsmK6CYWucQZXZYme1rp2SsT5Vn16H7r147AZFGqYLbb74nGkqAw2ft5f1e+2NmCZ3bSRs3ssmmyFrCd7Eb2b+ZSdlCZvq5GAEJrc6nKC2KG4s0QvPnEm1R3OXyROd8OatlvHdU/7o0ENMJKWQ4h9IeBoXdsq0aYepAuDEmLNLvnxXaeWnnYCQAekEEpksnZypwHtz653PooKMS2LYgtINzjCReVn0UWAc9zjM4ECZT94B68vzUoEuzslnx7BENsOSDFiQITLpyOgRgMYGOPkCwZTaRtQUVe3PVzfdPajWAMSu9nt2DKcehO3zpjiccyDfJAdgqJvBWAbWVfDWthV7ZB32xOhVTVbw1fxPnv7rcMmeWB4LVLniePf7m2fpSBFlV39bsOtHTxBgm6xBjIfd2HiZNg="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'